paths:
  reviews_data_path: data/processed/train_reviews.json
  test_reviews_path: data/processed/test_reviews.json
  users_data_path: data/unprocessed/yelp_academic_dataset_user.json
  businesses_data_path: data/unprocessed/yelp_academic_dataset_business.json
  unprocessed_reviews_path: data/unprocessed/yelp_academic_dataset_review.json
  user_id_map_path: saved_models/user_id_map.pkl
  business_id_map_path: saved_models/business_id_map.pkl
  category_map_path: saved_models/category_map.pkl
  best_model_path: saved_models/best_model.pt
training:
  batch_size: 1024
  epochs: 10
  learning_rate: 0.001
model:
  output_dim: 32
  user_tower:
    id_embedding_dim: 16
    n_continuous_features: 21
    hidden_layers:
    - 64
    - 32
  item_tower:
    id_embedding_dim: 16
    n_continuous_features: 13 # <-- THE ONLY CHANGE NEEDED!
    hidden_layers:
    - 64
    - 32
    category_embedding_dim: 16
    max_categories: 10 # Max categories per restaurant (for padding)
  interaction_mlp:
      hidden_layers: [64, 32] # 交互MLP的隐藏层结构
      dropout: 0.3              # 交互MLP的Dropout率
      
  n_users: 144898
  n_businesses: 13037
  n_categories: 1103

# 所有主题: [
# '产品与餐饮质量', '价格与价值', '健康与安全', '员工服务与态度', 
# '地理位置与便利性', '场所环境与氛围', '忠诚度与长期关系', '效率与速度', 
# '问题解决与管理', '额外体验与设施', '餐饮/专业服务质量'
# ]